bai3.3/bai3.3/Models/Country.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace bai3._3.Models
{
    public class Country
    {
        public string ID { get; set; }
        public string Name { get; set; }
    }
}

bai3.3/bai3.3/Controllers/HTMLHelperController.cs
using bai3._3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bai3._3.Controllers
{
    public class HTMLHelperController : Controller
    {
        // GET: HTMLHelper
        public ActionResult FormRegister()
        {
            // tạo list cho droplist
            ViewBag.listCountry = new List<Country>()
            {
                new Country() { ID = "0", Name = "-- Chọn Quốc Gia --" },
                new Country() { ID = "VN", Name = "Việt Nam" },
                new Country() { ID = "AT", Name = "AUSTRALIA" },
                new Country() { ID = "UK", Name = "Anh" },
                new Country() { ID = "FR", Name = "Pháp" },
                new Country() { ID = "US", Name = "Mỹ" },
                new Country() { ID = "KP", Name = "Hàn Quốc" },
                new Country() { ID = "HU", Name = "Hồng Kong" },
                new Country() { ID = "CN", Name = "Trung Quốc" },
            };
            return View();
        }
        public ActionResult Register()
        {
            // lấy giá trị được các trường đẩy lên server khi submit
            string fvr = "";
            TempData["UName"] = Request["txtUName"];
            TempData["Pass"] = Request["txtPass"];
            TempData["FName"] = Request["txtFName"];
            TempData["Gender"] = Request["Gender"].ToString();
            TempData["Address"] = Request["txtAddress"];
            TempData["Email"] = Request["txtEmail"];
            TempData["Country"] = Request["Country"];
            if (Request["Reading"].ToString().Contains("true")) fvr
+= "Reading ,";
            if (Request["Shopping"].ToString().Contains("true")) fvr +=
            "Shopping ,";
            if (Request["Sport"].ToString().Contains("true")) fvr += "Sport,";

TempData["Favourist"] = fvr;

            return View();
        }
        }
}

bai3.3/bai3.3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bai3._3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

bai3.3/bai3.3/Views/HTMLHelper/FormRegister.cshtml
@{
    ViewBag.Title = "FormRegister";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Đăng ký thành viên</h2>
@{
    Html.BeginForm("Register", "HTMLHelper", FormMethod.Get);
    <table class="table table-bordered">
        <tr>
            <td>@Html.Label("Tên đăng nhập")</td>
            <td>@Html.TextBox("txtUName")</td>
        </tr>
        <tr>
            <td>@Html.Label("Mật khẩu")</td>
            <td>@Html.Password("txtPass")</td>
        </tr>
        <tr>
            <td>@Html.Label("Nhập lại mật khẩu")</td>
            <td>@Html.Password("txCfPass")</td>
        </tr>
        <tr>
            <td>@Html.Label("Họ và tên")</td>
            <td>@Html.TextBox("txtFName")</td>
        </tr>
        <tr>
            <td>@Html.Label("Ngày sinh")</td>
            <td><input type="date" name="BDay" /></td>
        </tr>
        <tr>
            <td>@Html.Label("Giới tính")</td>
            <td>
                @Html.RadioButton("Gender", "Name", true) Nam
                @Html.RadioButton("Gender", "Nữ") Nữ
            </td>
        </tr>
        <tr>
            <td>@Html.Label("Địa chỉ")</td>
            <td>@Html.TextArea("txtAddress")</td>
        </tr>
        <tr>
            <td>@Html.Label("Email")</td>
            <td>@Html.TextBox("txtEmail")</td>
        </tr>
        <tr>
            <td>@Html.Label("Quốc gia")</td>
            <td>
                @Html.DropDownList("Country", new
        SelectList(ViewBag.listCountry, "ID", "Name"))
        </td>
    </tr>
    <tr>
        <td>@Html.Label("Sở thích")</td>
        <td>
            @Html.CheckBox("Reading") Đọc sách
        @Html.CheckBox("Shopping") Mua sắm @Html.CheckBox("Sport") Thể thao
    </td>
</tr>
<tr>
    <td></td>
    <td><input type="submit" value="Đăng Ký" /></td>
</tr>
</table>
Html.EndForm();
}

bai3.3/bai3.3/Views/HTMLHelper/Register.cshtml
@{
    ViewBag.Title = "SubmitForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin đăng ký</h2>
<table class="table table-bordered">
    <tr>
        <td>UserName :</td>
        <td>@TempData["UName"]</td>
    </tr>
    <tr>
        <td>Password :</td>
        <td>@TempData["Pass"]</td>
    </tr>
    <tr>
        <td>Full Name :</td>
        <td>@TempData["FName"]</td>
    </tr>
    <tr>
        <td>Gender :</td>
        <td>@TempData["Gender"]</td>
    </tr>
    <tr>
        <td>Address :</td>
        <td>@TempData["Address"]</td>
    </tr>
    <tr>
        <td>Email :</td>
        <td>@TempData["Email"]</td>
    </tr>
    <tr>
        <td>Country :</td>
        <td>@TempData["Country"]</td>
    </tr>
    <tr>
        <td>Favourist :</td>
        <td>@TempData["Favourist"]</td>
    </tr>
</table>

bai3.3/bai3.3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

bai3.3/bai3.3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

bai3.3/bai3.3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

bai3.3/bai3.3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-
                        toggle="collapse" data-target=".navbar-collapse">

                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DEVMASTER.vn-HTML Helper", "Index",
                "Home", new { area = "" }, new { @class = "navbar-brand" })
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Đăng ký", "FormRegister",
                "HTMLHelper")
                                </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>